/**
 * Universal Property Groups
 *
 * Only truly universal properties are defined here. Currently only "Color" is universal
 * because color is relevant across all store types and requires hex codes for proper display.
 *
 * All other properties (Size, Material, Volume, Scent, etc.) are store-specific and should
 * be generated by AI based on the store context. This ensures:
 * - Beauty stores get properties like "Volume", "Scent", "Skin Type"
 * - Fashion stores get properties like "Size", "Fabric", "Fit"
 * - Furniture stores get properties like "Material", "Dimensions", "Style"
 *
 * The color palette is comprehensive to cover most color names AI might generate.
 */

import type { CachedPropertyGroup } from "../types/index.js";

/**
 * Comprehensive color options with hex codes
 * These are curated to look good in storefront and cover common color names
 */
const COLOR_OPTIONS: Array<{ name: string; hex: string }> = [
    // Neutrals
    { name: "Black", hex: "#1a1a1a" },
    { name: "White", hex: "#ffffff" },
    { name: "Gray", hex: "#6b7280" },
    { name: "Charcoal", hex: "#374151" },
    { name: "Ivory", hex: "#fffff0" },
    { name: "Cream", hex: "#fffdd0" },
    { name: "Beige", hex: "#f5f5dc" },
    { name: "Taupe", hex: "#483c32" },

    // Wood tones
    { name: "Natural Oak", hex: "#c9a66b" },
    { name: "Oak", hex: "#c9a66b" },
    { name: "Walnut", hex: "#5d432c" },
    { name: "Cherry", hex: "#6b2d2d" },
    { name: "Mahogany", hex: "#4a0000" },
    { name: "Pine", hex: "#d4a76a" },
    { name: "Espresso", hex: "#3c2415" },
    { name: "Teak", hex: "#b08d57" },
    { name: "Ash", hex: "#b2beb5" },
    { name: "Birch", hex: "#f5deb3" },
    { name: "Maple", hex: "#c5833b" },
    { name: "Ebony", hex: "#555d50" },
    { name: "Rosewood", hex: "#65000b" },
    { name: "Cedar", hex: "#a0522d" },

    // Standard colors
    { name: "Red", hex: "#dc2626" },
    { name: "Blue", hex: "#2563eb" },
    { name: "Green", hex: "#16a34a" },
    { name: "Yellow", hex: "#eab308" },
    { name: "Orange", hex: "#ea580c" },
    { name: "Purple", hex: "#9333ea" },
    { name: "Pink", hex: "#ec4899" },
    { name: "Brown", hex: "#78350f" },

    // Rich colors
    { name: "Navy", hex: "#1e3a5f" },
    { name: "Forest Green", hex: "#228b22" },
    { name: "Burgundy", hex: "#722f37" },
    { name: "Terracotta", hex: "#e2725b" },
    { name: "Slate Blue", hex: "#6a5acd" },
    { name: "Olive", hex: "#808000" },
    { name: "Teal", hex: "#008080" },
    { name: "Coral", hex: "#ff7f50" },
    { name: "Indigo", hex: "#4b0082" },
    { name: "Maroon", hex: "#800000" },
    { name: "Turquoise", hex: "#40e0d0" },
    { name: "Lavender", hex: "#e6e6fa" },
    { name: "Salmon", hex: "#fa8072" },
    { name: "Mint", hex: "#98fb98" },
    { name: "Mustard", hex: "#ffdb58" },
    { name: "Plum", hex: "#dda0dd" },
    { name: "Rust", hex: "#b7410e" },
    { name: "Sand", hex: "#c2b280" },
    { name: "Sage", hex: "#bcb88a" },
    { name: "Slate", hex: "#708090" },

    // Metals
    { name: "Brass", hex: "#b5a642" },
    { name: "Bronze", hex: "#cd7f32" },
    { name: "Silver", hex: "#c0c0c0" },
    { name: "Copper", hex: "#b87333" },
    { name: "Gold", hex: "#ffd700" },
    { name: "Chrome", hex: "#dbe4eb" },
    { name: "Nickel", hex: "#727472" },
    { name: "Brushed Steel", hex: "#8b8d8e" },

    // Fabric/Textile colors
    { name: "Denim", hex: "#1560bd" },
    { name: "Khaki", hex: "#c3b091" },
    { name: "Tan", hex: "#d2b48c" },
    { name: "Camel", hex: "#c19a6b" },
    { name: "Linen", hex: "#faf0e6" },
    { name: "Charcoal Gray", hex: "#36454f" },

    // Additional colors for comprehensive coverage
    { name: "Rose", hex: "#ff007f" },
    { name: "Magenta", hex: "#ff00ff" },
    { name: "Cyan", hex: "#00ffff" },
    { name: "Aqua", hex: "#00ffff" },
    { name: "Lime", hex: "#32cd32" },
    { name: "Violet", hex: "#8b00ff" },
    { name: "Mauve", hex: "#e0b0ff" },
    { name: "Peach", hex: "#ffcba4" },
    { name: "Apricot", hex: "#fbceb1" },
    { name: "Champagne", hex: "#f7e7ce" },
    { name: "Pearl", hex: "#eae0c8" },
    { name: "Midnight", hex: "#191970" },
    { name: "Cobalt", hex: "#0047ab" },
    { name: "Azure", hex: "#007fff" },
    { name: "Sky Blue", hex: "#87ceeb" },
    { name: "Baby Blue", hex: "#89cff0" },
    { name: "Royal Blue", hex: "#4169e1" },
    { name: "Emerald", hex: "#50c878" },
    { name: "Jade", hex: "#00a86b" },
    { name: "Hunter Green", hex: "#355e3b" },
    { name: "Kelly Green", hex: "#4cbb17" },
    { name: "Sea Green", hex: "#2e8b57" },
    { name: "Scarlet", hex: "#ff2400" },
    { name: "Crimson", hex: "#dc143c" },
    { name: "Ruby", hex: "#e0115f" },
    { name: "Wine", hex: "#722f37" },
    { name: "Amber", hex: "#ffbf00" },
    { name: "Honey", hex: "#eb9605" },
    { name: "Chocolate", hex: "#7b3f00" },
    { name: "Mocha", hex: "#967969" },
    { name: "Coffee", hex: "#6f4e37" },
    { name: "Graphite", hex: "#383838" },
    { name: "Pewter", hex: "#8f8f8f" },
    { name: "Platinum", hex: "#e5e4e2" },
    { name: "Onyx", hex: "#353935" },
    { name: "Jet Black", hex: "#0a0a0a" },
    { name: "Snow White", hex: "#fffafa" },
    { name: "Off White", hex: "#faf0e6" },
    { name: "Eggshell", hex: "#f0ead6" },
];

/**
 * Universal property groups - only properties that apply across ALL store types
 *
 * Currently only Color is universal because:
 * 1. Color is relevant for products in any domain (beauty, fashion, furniture, electronics, etc.)
 * 2. Color requires hex codes for proper Shopware display
 * 3. The AI can reuse these predefined colors with correct hex values
 *
 * All other properties are domain-specific and should be AI-generated:
 * - Beauty: Volume, Scent, Skin Type, Hair Type
 * - Fashion: Size, Fabric, Fit, Length
 * - Furniture: Material, Dimensions, Style
 * - Electronics: Storage, Screen Size, Connectivity
 */
export const UNIVERSAL_PROPERTY_GROUPS: CachedPropertyGroup[] = [
    {
        name: "Color",
        slug: "color",
        displayType: "color",
        options: COLOR_OPTIONS.map((c) => c.name),
        colorHexCodes: Object.fromEntries(COLOR_OPTIONS.map((c) => [c.name, c.hex])),
        createdAt: "2025-01-01T00:00:00.000Z",
        source: "fixture",
    },
];

/**
 * Color hex lookup map for quick access
 */
export const COLOR_HEX_MAP: Record<string, string> = Object.fromEntries(
    COLOR_OPTIONS.map((c) => [c.name.toLowerCase(), c.hex])
);

/**
 * Get hex code for a color name (case-insensitive)
 */
export function getColorHexCode(colorName: string): string | undefined {
    return COLOR_HEX_MAP[colorName.toLowerCase()];
}

/**
 * Get all universal property groups
 */
export function getUniversalPropertyGroups(): CachedPropertyGroup[] {
    return UNIVERSAL_PROPERTY_GROUPS;
}
